# Generated by Django 3.0.4 on 2021-02-11 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20210124_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/mobile/'),
        ),
        migrations.CreateModel(
            name='PhoneImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_images', models.ImageField(blank=True, null=True, upload_to='images/mobile/')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile', to='phones.Phone')),
            ],
        ),
    ]
