# Generated by Django 3.0.4 on 2021-02-11 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_auto_20210211_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneimages',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_images', to='phones.Phone'),
        ),
    ]
