# Generated by Django 3.0.4 on 2020-11-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='availabel',
            new_name='available',
        ),
    ]
