# Generated by Django 3.0.4 on 2020-12-12 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201207_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='products/')),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.Items')),
            ],
        ),
    ]
