# Generated by Django 3.0.4 on 2020-12-13 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Items'),
        ),
    ]
