# Generated by Django 3.0.4 on 2021-01-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210119_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='items',
            name='slug',
        ),
    ]
